-- This is the project's first migration. No prior migration has ever been
-- applied to any environment (see herledger-app/README.md "Current Project
-- Status": "PostgreSQL schema | Defined — migrations not yet applied to any
-- environment"), so this single migration creates the full schema as it
-- stands after this PR, rather than only the settings-panel delta.
--
-- Hand-written rather than generated by `prisma migrate dev`: the CLI
-- pinned in this repo (prisma@7.9.1) refuses to parse the schema's
-- `datasource { url = env("DATABASE_URL") }` block (Prisma 7 deprecated
-- that property — see prisma/schema.prisma), a pre-existing issue
-- unrelated to this PR (reproducible on an unmodified `main`). This SQL
-- was authored to match Prisma's standard PostgreSQL migration output for
-- the field/attribute mappings declared in schema.prisma.

-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('PaymentReceived', 'PaymentSent', 'InvoiceSettled', 'CommitmentFulfilled');

-- CreateEnum
CREATE TYPE "EventStatus" AS ENUM ('Pending', 'Verified', 'Disputed', 'Revoked');

-- CreateEnum
CREATE TYPE "AttestationStatus" AS ENUM ('Active', 'Revoked');

-- CreateEnum
CREATE TYPE "NotificationEventType" AS ENUM ('NewAttestation', 'DisputeResolution', 'BusinessDeactivation');

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "name" TEXT,
    "image" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "accounts" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMPTZ,
    "refreshTokenExpiresAt" TIMESTAMPTZ,
    "scope" TEXT,
    "idToken" TEXT,
    "password" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verifications" (
    "id" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "verifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "business_profiles" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "walletAddress" TEXT,
    "displayName" TEXT NOT NULL,
    "metadataHash" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "business_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "financial_events" (
    "id" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "eventType" "EventType" NOT NULL,
    "assetAddress" TEXT NOT NULL,
    "amount" TEXT NOT NULL,
    "stellarReference" TEXT NOT NULL,
    "metadataHash" TEXT NOT NULL,
    "status" "EventStatus" NOT NULL DEFAULT 'Pending',
    "ledgerSequence" INTEGER NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "financial_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attestations" (
    "id" TEXT NOT NULL,
    "attestationId" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "attesterAddress" TEXT NOT NULL,
    "claimHash" TEXT NOT NULL,
    "status" "AttestationStatus" NOT NULL DEFAULT 'Active',
    "ledgerSequence" INTEGER NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "attestations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_preferences" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "eventType" "NotificationEventType" NOT NULL,
    "email" BOOLEAN NOT NULL DEFAULT true,
    "inApp" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "personal_access_tokens" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "prefix" TEXT NOT NULL,
    "lastUsedAt" TIMESTAMPTZ,
    "revokedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "personal_access_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "stellar_transactions" (
    "hash" TEXT NOT NULL,
    "ledgerSequence" INTEGER NOT NULL,
    "successful" BOOLEAN NOT NULL,
    "sourceAddress" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "stellar_transactions_pkey" PRIMARY KEY ("hash")
);

-- CreateTable
CREATE TABLE "indexer_checkpoints" (
    "id" TEXT NOT NULL,
    "stream" TEXT NOT NULL,
    "lastLedger" INTEGER NOT NULL,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "indexer_checkpoints_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_key" ON "sessions"("token");

-- CreateIndex
CREATE INDEX "sessions_userId_idx" ON "sessions"("userId");

-- CreateIndex
CREATE INDEX "accounts_userId_idx" ON "accounts"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "accounts_providerId_accountId_key" ON "accounts"("providerId", "accountId");

-- CreateIndex
CREATE UNIQUE INDEX "verifications_identifier_value_key" ON "verifications"("identifier", "value");

-- CreateIndex
CREATE UNIQUE INDEX "business_profiles_userId_key" ON "business_profiles"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "business_profiles_businessId_key" ON "business_profiles"("businessId");

-- CreateIndex
CREATE UNIQUE INDEX "business_profiles_walletAddress_key" ON "business_profiles"("walletAddress");

-- CreateIndex
CREATE INDEX "business_profiles_walletAddress_idx" ON "business_profiles"("walletAddress");

-- CreateIndex
CREATE INDEX "business_profiles_businessId_idx" ON "business_profiles"("businessId");

-- CreateIndex
CREATE UNIQUE INDEX "financial_events_eventId_key" ON "financial_events"("eventId");

-- CreateIndex
CREATE INDEX "financial_events_businessId_idx" ON "financial_events"("businessId");

-- CreateIndex
CREATE INDEX "financial_events_ledgerSequence_idx" ON "financial_events"("ledgerSequence");

-- CreateIndex
CREATE INDEX "financial_events_status_idx" ON "financial_events"("status");

-- CreateIndex
CREATE UNIQUE INDEX "attestations_attestationId_key" ON "attestations"("attestationId");

-- CreateIndex
CREATE INDEX "attestations_eventId_idx" ON "attestations"("eventId");

-- CreateIndex
CREATE INDEX "attestations_attesterAddress_idx" ON "attestations"("attesterAddress");

-- CreateIndex
CREATE INDEX "notification_preferences_userId_idx" ON "notification_preferences"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "notification_preferences_userId_eventType_key" ON "notification_preferences"("userId", "eventType");

-- CreateIndex
CREATE UNIQUE INDEX "personal_access_tokens_tokenHash_key" ON "personal_access_tokens"("tokenHash");

-- CreateIndex
CREATE INDEX "personal_access_tokens_userId_idx" ON "personal_access_tokens"("userId");

-- CreateIndex
CREATE INDEX "stellar_transactions_ledgerSequence_idx" ON "stellar_transactions"("ledgerSequence");

-- CreateIndex
CREATE INDEX "stellar_transactions_sourceAddress_idx" ON "stellar_transactions"("sourceAddress");

-- CreateIndex
CREATE UNIQUE INDEX "indexer_checkpoints_stream_key" ON "indexer_checkpoints"("stream");

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "business_profiles" ADD CONSTRAINT "business_profiles_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_events" ADD CONSTRAINT "financial_events_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "business_profiles"("businessId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attestations" ADD CONSTRAINT "attestations_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "financial_events"("eventId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "personal_access_tokens" ADD CONSTRAINT "personal_access_tokens_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
