import { randomBytes, createHmac, timingSafeEqual } from "node:crypto";

// ---------------------------------------------------------------------------
// Personal access token generation + hashing
//
// Server-only (uses node:crypto) — imported via the "@herledger/config/tokens"
// subpath export, deliberately kept out of the main "@herledger/config"
// barrel so client components that only need getPublicEnv() never pull
// node:crypto into a browser bundle.
// ---------------------------------------------------------------------------

const TOKEN_PREFIX = "hl_pat_";
/** 256 bits of entropy — high enough that unsalted-but-peppered hashing is safe (see hashPersonalAccessToken). */
const TOKEN_SECRET_BYTES = 32;
/** Non-secret chars of the token shown in the UI so a user can tell tokens apart, e.g. "hl_pat_ab12cd34". */
const DISPLAY_PREFIX_LENGTH = TOKEN_PREFIX.length + 8;

export interface GeneratedPersonalAccessToken {
  /** Plaintext token value. Shown to the user exactly once, at creation time — never persisted or logged. */
  token: string;
  /** Non-secret prefix, safe to store and display for token identification. */
  prefix: string;
}

/**
 * Generates a new personal access token. The returned `token` is the only
 * time the plaintext value is ever available — callers must hash it with
 * `hashPersonalAccessToken` before persisting anything, and show `token` to
 * the user immediately (it cannot be recovered later).
 */
export function generatePersonalAccessToken(): GeneratedPersonalAccessToken {
  const secret = randomBytes(TOKEN_SECRET_BYTES).toString("base64url");
  const token = `${TOKEN_PREFIX}${secret}`;
  return { token, prefix: token.slice(0, DISPLAY_PREFIX_LENGTH) };
}

/**
 * Hashes a personal access token for storage/lookup.
 *
 * This is HMAC-SHA256 keyed with a server-side pepper (in practice the
 * application's BETTER_AUTH_SECRET — see apps/web/lib/auth/server.ts and
 * indexer/src/api/auth/personal-access-token.ts), not plain unsalted SHA-256.
 *
 * Why unsalted SHA-256 would already be defensible here: personal access
 * tokens are 256-bit random secrets generated by `generatePersonalAccessToken`,
 * not user-chosen passwords. Salting exists to defeat rainbow tables and
 * cross-user dictionary attacks against *low-entropy* secrets — neither
 * concern applies to a high-entropy random token, and a lookup by hash
 * needs to be deterministic (a per-token salt would require storing the
 * salt anyway, which buys nothing extra here since the plaintext offers no
 * exploitable pattern to precompute against).
 *
 * The pepper protects a narrower, more realistic risk instead: if the
 * personal_access_tokens table alone is exfiltrated (e.g. a scoped SQL
 * injection or a stale backup) without the application's runtime secret,
 * the attacker holds bare SHA-256 digests of 256-bit values -- already
 * infeasible to invert, but keying with a secret the DB never sees adds a
 * second factor an attacker needs before a stolen hash is usable for
 * anything (e.g. crafting a request that presents a hash directly to a
 * naive comparison path). Reusing BETTER_AUTH_SECRET means no new secret to
 * provision, distribute, or rotate across apps/web and indexer.
 */
export function hashPersonalAccessToken(token: string, pepper: string): string {
  return createHmac("sha256", pepper).update(token).digest("hex");
}

/**
 * Constant-time comparison of a presented token against a stored hash.
 * Always hash-then-compare (never compare plaintext tokens directly) so
 * that neither the token nor a timing side-channel on the hash comparison
 * can leak information about the stored value.
 */
export function verifyPersonalAccessTokenHash(
  token: string,
  pepper: string,
  storedHash: string
): boolean {
  const computed = Buffer.from(hashPersonalAccessToken(token, pepper), "hex");
  let stored: Buffer;
  try {
    stored = Buffer.from(storedHash, "hex");
  } catch {
    return false;
  }
  if (computed.length !== stored.length) return false;
  return timingSafeEqual(computed, stored);
}
